### ISSUE TITLE
https://github.com/Aircoookie/WLED/releases/download/v0.12.0/WLED_0.12.0_ESP32.bin

### ISSUE THREAD

**Issue by soanstengend** [Aircoookie/aircoookie#1]

**Comment by Aircoookie** [comment]
?

**Comment by soanstengend** [comment]
Hello Please excuse me if I make something clear about what is not right or was or wrong. I have I don't know what I'm doing I downloaded this yesterday to fumble three but it turns out to be more difficult for me than I thought.Gesendet mit der WEB.DE Mail AppAm 12.11.21 um 09:47 schrieb Christian Schwinne
                
            
            
                
                    Von: "Christian Schwinne" ***@***.***>Datum: 12. November 2021An: "Aircoookie/aircoookie" ***@***.***>Cc: "soanstengend" ***@***.***>,"Author" ***@***.***>Betreff: Re: [Aircoookie/aircoookie] https://github.com/Aircoookie/WLED/releases/download/v0.12.0/WLED_0.12.0_ESP32.bin (Issue #1)
                
                
Closed #1.
